### ISSUE TITLE
Comment lines

### ISSUE THREAD

**Issue by amongthestones** [raamdev/independent-publisher-child#1]
Hi Raam! Not sure if this is an appropriate place for my question. I'm interested in removing the horizontal and vertical lines between comments in a thread and seeing what that looks like. I'd prefer to use a child theme to not break functionality with Independent Publisher. Is this possible using the child theme? Thanks!

— Jimmy

**Comment by raamdev** [comment]
@jimmymansaray Hey! 😄

You can actually achieve that with a little CSS:

```css
.commentlist .thread-even, .commentlist .thread-odd,
.commentlist .thread-even ul.children, .commentlist .thread-odd ul.children {
     border-left: 0 !important;
     border-top: 0 !important;
}
```

![2017-03-23_17-08-29](https://cloud.githubusercontent.com/assets/53005/24270390/5b83c644-0feb-11e7-81a4-7004c3db0075.png)


That can go in a Child Theme `style.css` or you can just use something like Jetpack's Edit CSS module (**Appearance → Edit CSS**).

I hope this helps!
